myshop/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from .import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

app_name = 'account'


urlpatterns = [

    path('register/', views.registerView, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.accountActivateView, name="activate"),

    # User DashBoard
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('profile/edit/', views.userEditView, name='edit-user-details'),
    path('profile/delete_user/', views.userDeleteView, name='delete-user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/delete_confirm.html"), name='delete-confirmation'),

    # login classed based views
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html',), name='logout'),


    # Reset Password Process
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="account/password_reset/reset_form.html",
        success_url='password_reset_email_confirm',
        email_template_name='account/password_reset/reset_email.html',
        form_class=PwdResetForm), 
        name='pwdreset'),

    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset/reset_confirm.html',
        success_url='/account/password_reset_complete/',
        form_class=PwdResetConfirmForm),
        name="password_reset_confirm"),

    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),

    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),

    # Addresses
    path("addresses/", views.addressView, name="addresses"),
    path("add_address/", views.addAddressView, name="add_address"),
    path("addresses/edit/<slug:id>/", views.editAddressView, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.deleteAddressView, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.defaultAddressView, name="set_default"),

]

myshop/basket/urls.py
from django.urls import path
from .import views

app_name = 'basket'

urlpatterns = [
    path('', views.basketSummaryView, name='basket-summary'),
    path('add/', views.basketAddView, name='basket-add'),
    path('delete/', views.basketdeleteView, name='basket-delete'),
    path('update/', views.basketUpdateView, name='basket-update'),

]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('account/', include('account.urls', namespace='account')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/order/urls.py
from django.urls import path
from .import views


app_name = 'order'


urlpatterns = [ ]

myshop/product/urls.py
from django.urls import path
from .import views

app_name = 'product'

urlpatterns = [
    path('', views.homePageView, name='home-page'),
    path('<slug:slug>', views.productDetailView, name="product-detail"),
    path('shop/<slug:categorySlug>/', views.categoryDetailView, name='category-detail'),

]

myshop/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  <!-- link my external css file -->
  <link href="{% static 'css/base.css' %}" type="text/css" rel="stylesheet">
  <link href="{% block stylesheet %}{% endblock stylesheet %}" type="text/css" rel="stylesheet">


  <!-- Jquery cdn -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <title>{% block 'title' %}PalavPoshak{% endblock %}</title>
</head>

<body>


  <header class="pb-3">
    <!-- Nav bar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark  border-bottom">

      <div class="container-fluid px-md-4">
        <div class="d-flex w-100 navbar-collapse">
          <a class="navbar-brand" href="{% url 'product:home-page' %}">
            <img src="{% static 'logo/logo.png' %}" alt="" width="45px">
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  <b>Categories</b> 
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for c in categories %}
                  <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                
                  {% endfor %}
                </div>

              </li>

              {% if user.is_authenticated %}
              <li class="nav-item">
                <p class="nav-link">Hi {{user.user_name}}</p>
              </li>
              {% endif %}
            </ul>
          </div>



          <!-- Cart icon here -->
          <a type="button" role="button" title="My Cart" href="{% url 'basket:basket-summary' %}"
            class="btn btn-outline-info border-0 basket-btn">

            {% with total_qty=basket|length %}
            <div id="basketQty" class="d-inline-flex basket-qty">
              {% if total_qty > 0 %}
              {{total_qty}}
              {% else %}
              0
              {% endif %}
            </div>
            {% endwith %}
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="35" height="25" fill="currentColor" class="bi bi-cart3"
                viewBox="0 0 16 16">
                <path
                  d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
              </svg>

            </div>
            <span class="fs15 fw500">Cart</span>
          </a>

          <!-- User dashboard Icon here -->
          <a type="button" role="button" href="{% url 'account:dashboard' %}"
            class="btn btn-outline-info border-0 basket-btn">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-person"
                viewBox="0 0 16 16">
                <path
                  d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
              </svg>
            </div>
            <span class="fs15 fw500">Account</span>
          </a>

          <!-- login Logout -->
          {% if user.is_authenticated %}
          <a type="button" role="button" href="{% url 'account:logout' %}"
            class="btn btn-outline-info border-0 basket-btn">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                class="bi bi-door-closed" viewBox="0 0 16 16">
                <path
                  d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
              </svg>
            </div>
            <span class="fs15 fw500">Logout</span>
          </a>
          {% else %}
          <a type="button" role="button" href="{% url 'account:login' %}"
            class="btn btn-outline-info border-0 basket-btn">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                class="bi bi-door-closed" viewBox="0 0 16 16">
                <path
                  d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
              </svg>
            </div>
            <span class="fs15 fw500">Login</span>
          </a>
          {% endif %}


        </div>



        <form class="d-flex w-100 d-md-none">
          <input class="form-control me-2" type="search" placeholder="Search products or FAQ" aria-label="Search">
          <button class="btn btn-outline-secondary" type="submit">Search</button>
        </form>

      </div>
    </nav>
  </header>

  <!-- Flashed messages -->
  {% if messages %}
  {% for message in messages %}

  {% ifequal message.tags "success" %}
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path
        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
    </symbol>
  </svg>

  <div class="alert alert-success align-items-center text-center" role="alert" style="font-family: 'Amiri', serif;">
    <div class="d-inline-flex p-3">
      <div class="p-2">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
          <use xlink:href="#check-circle-fill" /></svg>
      </div>
      <div class="p-2">
        <h4 class="alert-heading">Cogratulation!</h4>
      </div>
    </div>
    <p>{{ message }}</p>
  </div>
  {% else %}
  <div class="text-center alert alert-{{ message.tags }} alert-dismissible fade show">
    {{ message }}
  </div>
  {% endifequal %}
  {% endfor %}
  {% endif %}

  <main class="pt-1">
    <!-- main content -->
      {% block 'mainContent' %}
      
      {% endblock 'mainContent' %}

  </main>




  <footer class="container-fluid p-5 footer">
    <div class="row">
      <div class="col-12 col-md">
        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-basket-fill"
          viewBox="0 0 24 24">
          <path
            d="M5.071 1.243a.5.5 0 0 1 .858.514L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 6h1.717L5.07 1.243zM3.5 10.5a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3z" />
        </svg>

        <h5 class="d-block mb-3 text-muted">copyright&copy;2021</h5>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Cool stuff</a></li>
          <li><a class="link-secondary" href="#">Random feature</a></li>
          <li><a class="link-secondary" href="#">Team feature</a></li>
          <li><a class="link-secondary" href="#">Stuff for developers</a></li>
          <li><a class="link-secondary" href="#">Another one</a></li>
          <li><a class="link-secondary" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Resource name</a></li>
          <li><a class="link-secondary" href="#">Resource</a></li>
          <li><a class="link-secondary" href="#">Another resource</a></li>
          <li><a class="link-secondary" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Business</a></li>
          <li><a class="link-secondary" href="#">Education</a></li>
          <li><a class="link-secondary" href="#">Government</a></li>
          <li><a class="link-secondary" href="#">Gaming</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Team</a></li>
          <li><a class="link-secondary" href="#">Locations</a></li>
          <li><a class="link-secondary" href="#">Privacy</a></li>
          <li><a class="link-secondary" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
  <!-- <footer>
    <div class="footer-content">
        <h3>PalavPoshak</h3>
        <Complex>Simple is better than complex. Complex is better than complicated.</p>
    </div>
    <div class="footer-bottom">
        <p>copyright &copy;2021 PalavPoshak store, managed by <span>Bisma Parveen</span></p>
    </div>
</footer> -->


  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script> -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>


</body>

</html>

myshop/templates/home.html
{% extends 'base.html' %}
{% load static %}
<!-- Title Of page -->
{% block 'title' %}Palav Poshaak{% endblock 'title' %}
{% block stylesheet %}
{% static 'css/home.css' %}
{% endblock stylesheet %}

<!-- my Main Content block -->
{% block 'mainContent' %}



<!-- ------------ My All Products -->



<div class="container small-container">
    <h2 class='title'>All Products</h2>
    <div class="row">
        {% for product in products %}

        <div class="col-md-4 container-fluid vh-100 ">
            <div class="card cartelement" style="width: 18rem;">
                <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}"
                        alt="Card image cap"></a>
                <div class="card-body">
                        <h5 class="card-title">{{ product.title|slice:":30" }}...</h5>
                    <p class="card-text">₹ {{product.price}}</p>
                    <a href="{{ product.get_absolute_url }}">
                        <button id="addButton" value="{{product.id}}" type="button" class="btn btn-success btn-sm"><b>Buy Now</b></button>

                    </a>
                    
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>









{% endblock 'mainContent' %}