myshop/basket/urls.py
from django.urls import path
from .import views

app_name = 'basket'

urlpatterns = [
    path('', views.basketSummaryView, name='basket-summary'),
    path('add/', views.basketAddView, name='basket-add'),
    path('delete/', views.basketdeleteView, name='basket-delete'),
    path('update/', views.basketUpdateView, name='basket-update'),

]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('account/', include('account.urls', namespace='account')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/order/urls.py
from django.urls import path
from .import views


app_name = 'order'


urlpatterns = [ ]

myshop/product/urls.py
from django.urls import path
from .import views

app_name = 'product'

urlpatterns = [
    path('', views.homePageView, name='home-page'),
    path('<slug:slug>', views.productDetailView, name="product-detail"),
    path('shop/<slug:categorySlug>/', views.categoryDetailView, name='category-detail'),

]

myshop/product/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# I am creating product manager here for ProductModel, which will get only those product who's is_active status is True
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(isActive=True)


class CategoryModel(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.CharField(max_length=300)

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Categories'
        

    def get_absolute_url(self):
        return reverse('product:category-detail', args=[self.slug])

    def __str__(self):
        return self.name


class ProductModel(models.Model):
    
    category = models.ForeignKey(CategoryModel, related_name="product", on_delete=models.SET_NULL, blank=True, null=True)
    
    title = models.CharField(max_length=70)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.PositiveIntegerField()
    slug = models.SlugField(max_length=255, unique=True)
    # is_active = is product active so that it needs to be displayed on the site
    isActive = models.BooleanField(default=True,) 
    inStock = models.BooleanField(default=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # I am creating here model manager
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = "Products"
        ordering = ("-created",)   # -created: is stack, thats lastOrder will be shown first in the database

    def get_absolute_url(self):
        return reverse('product:product-detail', args=[self.slug])

    def __str__(self):
        return self.title

myshop/product/views.py
from django.shortcuts import render, get_object_or_404
from .models import CategoryModel, ProductModel


def homePageView(request):
    products = ProductModel.products.all()
    context ={'products':products, }
    return render(request, 'home.html', context)
    

def productDetailView(request, slug):
    product = get_object_or_404(ProductModel, slug=slug, inStock=True)
    context = {'product':product}
    return render(request, 'product/detailPage.html', context)


def categoryDetailView(request, categorySlug):
    category = get_object_or_404(CategoryModel, slug=categorySlug)
    products = ProductModel.products.filter(category=category)

    context ={'products':products, 'category':category}

    return render(request, 'product/categoryDetail.html', context)

myshop/templates/product/categoryDetail.html
{% extends 'base.html' %}
{% load static %}
<!-- Title Of page -->

{% block 'title' %}
{% if category %}{{ category.name }}{% else %}Category Page{% endif %}
{% endblock 'title' %}


{% block stylesheet %}
{% static 'css/home.css' %}
{% endblock stylesheet %}
<!-- my Main Content block -->
{% block 'mainContent' %}
<!-- This is card of my website -->
<div class="container mt-5 small-container">
    <h2 class='title'>Category: {{category.name|title}}</h2>
    <div class="row">
        {% for product in products %}
        <div class="col-md-4 container-fluid vh-100 ">
            <div class="card cartelement" style="width: 18rem;">
                <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}"
                        alt="Card image cap"></a>
                <div class="card-body">
                        <h5 class="card-title">{{ product.title|slice:":30" }}...</h5>
                    <p class="card-text">₹ {{product.price}}</p>
                    <a href="{{ product.get_absolute_url }}">
                        <button id="addButton" value="{{product.id}}" type="button" class="btn btn-success btn-sm"><b>Buy Now</b></button>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock 'mainContent' %}

myshop/templates/product/detailPage.html
{% extends 'base.html' %}

<!-- Title Of page -->
{% block 'title' %}
{% if product %}{{ product.title }}{% else %}Detail Page{% endif %}
{% endblock 'title' %}


<!-- my Main Content block -->
{% block 'mainContent' %}

<div class="container">
    <div class="row g-3"> 

        <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
            <div class="d-grip gap-2">
                <div class="d-flex d-flex-inline justify-content-between">
                    <div>
                        <span class="h3"> ₹ {{ product.price }} </span>
                        <p class="text-muted">(includes tax)</p>
                    </div>
                    <div class='form-outline'>
                        <label class="form-label" for="typeNumber">Quantity: </label>
                        <input type="number" id="selectQty" class="form-control" value="1" min="1" max="50" />
                    </div>
                </div>
                <hr>
                <button id="addButton" value="{{product.id}}" type="button" class="btn btn-success fw500"><b>Add to
                    Cart</b></button>
                <button id="add-to-wishlist" value="{{product.id}}" type="button" class="btn btn-success fw500"><b>Add
                    to
                    WishList</b></button>
            </div>
        </div>
        
        <div class="col-md-6 col-lg-6 m-1" style="background-color: #d5cfdff3;">
            <div class="card mb-3 border-0" style="background-color: #d5cfdff3; ">
                <div class="row g-0">
                    <div class="col-md-12">

                        <div class="card-body p-1">
                            <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
                            <div style="background-color: #d5cfdff3;">
                                <img src="{{ product.image.url }}" alt="Responsive Image" class="img-fluid mx-auto d-block" width="200px">
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

            <!--    --------For getting the size ---------------
                <select>
                <option value="">Select Size</option>
                <option>S</option>
                <option>M</option>
                <option>L</option>
                <option>XL</option>
                <option>XXL</option>
                <option>XXXL</option>
            </select> -->
            <!-- Input Text -->

<script>
    $(document).on('click', '#addButton', function (e) {
        // console.log('button pressed');
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket-add" %}',
            data: {
                productid: $('#addButton').val(),
                productQty: $('#selectQty').val(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            // After successfully submiting post request; our success function works;
            // which basically retuns the success response
            success: function (json) {
                document.getElementById("basketQty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    });
</script>

{% endblock 'mainContent' %}